// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Uac2ErrorCode`, `Uac2HotplugEvent`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

bool uac2IsAvailable() => RustLib.instance.api.crateApiUac2ApiUac2IsAvailable();

List<Uac2DeviceInfo> uac2ListDevices() =>
    RustLib.instance.api.crateApiUac2ApiUac2ListDevices();

Future<Uac2DeviceCapabilities> uac2GetDeviceCapabilities({
  required Uac2DeviceInfo device,
}) => RustLib.instance.api.crateApiUac2ApiUac2GetDeviceCapabilities(
  device: device,
);

Future<bool> uac2SelectDevice({required Uac2DeviceInfo device}) =>
    RustLib.instance.api.crateApiUac2ApiUac2SelectDevice(device: device);

Future<bool> uac2StartStreaming({required Uac2AudioFormat format}) =>
    RustLib.instance.api.crateApiUac2ApiUac2StartStreaming(format: format);

Future<bool> uac2StopStreaming() =>
    RustLib.instance.api.crateApiUac2ApiUac2StopStreaming();

Future<void> uac2Disconnect() =>
    RustLib.instance.api.crateApiUac2ApiUac2Disconnect();

Future<void> uac2SetVolume({required double volume}) =>
    RustLib.instance.api.crateApiUac2ApiUac2SetVolume(volume: volume);

double uac2GetVolume() => RustLib.instance.api.crateApiUac2ApiUac2GetVolume();

Future<void> uac2SetMute({required bool muted}) =>
    RustLib.instance.api.crateApiUac2ApiUac2SetMute(muted: muted);

bool uac2GetMute() => RustLib.instance.api.crateApiUac2ApiUac2GetMute();

class Uac2AudioFormat {
  final int sampleRate;
  final int bitDepth;
  final int channels;

  const Uac2AudioFormat({
    required this.sampleRate,
    required this.bitDepth,
    required this.channels,
  });

  @override
  int get hashCode =>
      sampleRate.hashCode ^ bitDepth.hashCode ^ channels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Uac2AudioFormat &&
          runtimeType == other.runtimeType &&
          sampleRate == other.sampleRate &&
          bitDepth == other.bitDepth &&
          channels == other.channels;
}

class Uac2DeviceCapabilities {
  final Uint32List supportedSampleRates;
  final Uint8List supportedBitDepths;
  final Uint16List supportedChannels;
  final String deviceType;

  const Uac2DeviceCapabilities({
    required this.supportedSampleRates,
    required this.supportedBitDepths,
    required this.supportedChannels,
    required this.deviceType,
  });

  @override
  int get hashCode =>
      supportedSampleRates.hashCode ^
      supportedBitDepths.hashCode ^
      supportedChannels.hashCode ^
      deviceType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Uac2DeviceCapabilities &&
          runtimeType == other.runtimeType &&
          supportedSampleRates == other.supportedSampleRates &&
          supportedBitDepths == other.supportedBitDepths &&
          supportedChannels == other.supportedChannels &&
          deviceType == other.deviceType;
}

class Uac2DeviceInfo {
  final int vendorId;
  final int productId;
  final String? serial;
  final String productName;
  final String manufacturer;
  final String? deviceName;

  const Uac2DeviceInfo({
    required this.vendorId,
    required this.productId,
    this.serial,
    required this.productName,
    required this.manufacturer,
    this.deviceName,
  });

  @override
  int get hashCode =>
      vendorId.hashCode ^
      productId.hashCode ^
      serial.hashCode ^
      productName.hashCode ^
      manufacturer.hashCode ^
      deviceName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Uac2DeviceInfo &&
          runtimeType == other.runtimeType &&
          vendorId == other.vendorId &&
          productId == other.productId &&
          serial == other.serial &&
          productName == other.productName &&
          manufacturer == other.manufacturer &&
          deviceName == other.deviceName;
}
